// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UsYyCzAEbiaSQRO0P1jxI-5k9OjMKvg',
    appId: '1:193737354174:web:23b33d62b845dced26a7ef',
    messagingSenderId: '193737354174',
    projectId: 'signup-813b6',
    authDomain: 'signup-813b6.firebaseapp.com',
    storageBucket: 'signup-813b6.appspot.com',
    measurementId: 'G-53WE6H7NT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Jk44qY3N24OkYoA7EVK_XiUmqhsUV94',
    appId: '1:193737354174:android:2f45dca6bf20ea9826a7ef',
    messagingSenderId: '193737354174',
    projectId: 'signup-813b6',
    storageBucket: 'signup-813b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRk1m72OJD9Kc4DX_OJMi8Sl2tPHM3EQ',
    appId: '1:193737354174:ios:bf9b545d3fcae17026a7ef',
    messagingSenderId: '193737354174',
    projectId: 'signup-813b6',
    storageBucket: 'signup-813b6.appspot.com',
    iosBundleId: 'com.example.healthsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRk1m72OJD9Kc4DX_OJMi8Sl2tPHM3EQ',
    appId: '1:193737354174:ios:77f4c7acdd6e76aa26a7ef',
    messagingSenderId: '193737354174',
    projectId: 'signup-813b6',
    storageBucket: 'signup-813b6.appspot.com',
    iosBundleId: 'com.example.healthsyncApp.RunnerTests',
  );
}
